FROM robotastic/trunk-recorder:latest

ENV UDEV=on

COPY config.json config.json
COPY UnitTags.csv UnitTags.csv
COPY talkgroups.csv talkgroups.csv
COPY transcribe.sh transcribe.sh
RUN chmod +x transcribe.sh


RUN apt-get update
RUN apt-get install -y jq
RUN apt-get install -y vim
