FROM robotastic/trunk-recorder:5.0.2

ENV UDEV=on

COPY config.json config.json
COPY berkeley_channels.csv berkeley_channels.csv
COPY transcribe.sh transcribe.sh
RUN chmod +x transcribe.sh

RUN apt-get update
RUN apt-get install -y jq
RUN apt-get install -y vim
