name: Fly Deploy
on:
  push:
    branches:
      - '**'
    paths:
      - Trunk-Transcribe/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Trunk-Transcribe
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
        
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Trunk-Transcribe
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
